#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at-spi2-atk
Version  : 2.30.1
Release  : 17
URL      : https://download.gnome.org/sources/at-spi2-atk/2.30/at-spi2-atk-2.30.1.tar.xz
Source0  : https://download.gnome.org/sources/at-spi2-atk/2.30/at-spi2-atk-2.30.1.tar.xz
Summary  : A GTK+ module that bridges ATK to D-Bus at-spi
Group    : Development/Tools
License  : LGPL-2.0
Requires: at-spi2-atk-lib = %{version}-%{release}
Requires: at-spi2-atk-license = %{version}-%{release}
BuildRequires : at-spi2-core-dev
BuildRequires : at-spi2-core-dev32
BuildRequires : atk-dev
BuildRequires : atk-dev32
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : dbus-dev32
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glib-dev32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libxml2-dev
BuildRequires : libxml2-dev32

%description
D-Bus AT-SPI
------------
This version of at-spi is a major break from version 1.x.
It has been completely rewritten to use D-Bus rather than
ORBIT / CORBA for its transport protocol.

%package dev
Summary: dev components for the at-spi2-atk package.
Group: Development
Requires: at-spi2-atk-lib = %{version}-%{release}
Provides: at-spi2-atk-devel = %{version}-%{release}
Requires: at-spi2-atk = %{version}-%{release}

%description dev
dev components for the at-spi2-atk package.


%package dev32
Summary: dev32 components for the at-spi2-atk package.
Group: Default
Requires: at-spi2-atk-lib32 = %{version}-%{release}
Requires: at-spi2-atk-dev = %{version}-%{release}

%description dev32
dev32 components for the at-spi2-atk package.


%package lib
Summary: lib components for the at-spi2-atk package.
Group: Libraries
Requires: at-spi2-atk-license = %{version}-%{release}

%description lib
lib components for the at-spi2-atk package.


%package lib32
Summary: lib32 components for the at-spi2-atk package.
Group: Default
Requires: at-spi2-atk-license = %{version}-%{release}

%description lib32
lib32 components for the at-spi2-atk package.


%package license
Summary: license components for the at-spi2-atk package.
Group: Default

%description license
license components for the at-spi2-atk package.


%prep
%setup -q -n at-spi2-atk-2.30.1
pushd ..
cp -a at-spi2-atk-2.30.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552261413
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir
pushd ../build32
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
meson --libdir=/usr/lib32 --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir
popd

%install
mkdir -p %{buildroot}/usr/share/package-licenses/at-spi2-atk
cp COPYING %{buildroot}/usr/share/package-licenses/at-spi2-atk/COPYING
pushd ../build32
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib32/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop
/usr/lib64/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/at-spi2-atk/2.0/atk-bridge.h
/usr/lib64/libatk-bridge-2.0.so
/usr/lib64/pkgconfig/atk-bridge-2.0.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libatk-bridge-2.0.so
/usr/lib32/pkgconfig/32atk-bridge-2.0.pc
/usr/lib32/pkgconfig/atk-bridge-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/modules/libatk-bridge.so
/usr/lib64/libatk-bridge-2.0.so.0
/usr/lib64/libatk-bridge-2.0.so.0.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/gtk-2.0/modules/libatk-bridge.so
/usr/lib32/libatk-bridge-2.0.so.0
/usr/lib32/libatk-bridge-2.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/at-spi2-atk/COPYING
