#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at-spi2-atk
Version  : 2.26.1
Release  : 11
URL      : https://download.gnome.org/sources/at-spi2-atk/2.26/at-spi2-atk-2.26.1.tar.xz
Source0  : https://download.gnome.org/sources/at-spi2-atk/2.26/at-spi2-atk-2.26.1.tar.xz
Summary  : ATK/D-Bus Bridge
Group    : Development/Tools
License  : LGPL-2.0
Requires: at-spi2-atk-lib
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : gettext
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : meson
BuildRequires : ninja
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(32atk)
BuildRequires : pkgconfig(32atspi-2)
BuildRequires : pkgconfig(32dbus-1)
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(32gmodule-2.0)
BuildRequires : pkgconfig(32gobject-2.0)
BuildRequires : pkgconfig(32libxml-2.0)
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(atspi-2)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3

%description
D-Bus AT-SPI
------------
This version of at-spi is a major break from version 1.x.
It has been completely rewritten to use D-Bus rather than
ORBIT / CORBA for its transport protocol.

%package dev
Summary: dev components for the at-spi2-atk package.
Group: Development
Requires: at-spi2-atk-lib
Provides: at-spi2-atk-devel

%description dev
dev components for the at-spi2-atk package.


%package dev32
Summary: dev32 components for the at-spi2-atk package.
Group: Default
Requires: at-spi2-atk-lib32
Requires: at-spi2-atk-dev

%description dev32
dev32 components for the at-spi2-atk package.


%package lib
Summary: lib components for the at-spi2-atk package.
Group: Libraries

%description lib
lib components for the at-spi2-atk package.


%package lib32
Summary: lib32 components for the at-spi2-atk package.
Group: Default

%description lib32
lib32 components for the at-spi2-atk package.


%prep
%setup -q -n at-spi2-atk-2.26.1
pushd ..
cp -a at-spi2-atk-2.26.1 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510233247
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1510233247
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)
/usr/lib32/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop
/usr/lib64/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/at-spi2-atk/2.0/atk-bridge.h
/usr/lib64/libatk-bridge-2.0.so
/usr/lib64/pkgconfig/atk-bridge-2.0.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libatk-bridge-2.0.so
/usr/lib32/pkgconfig/32atk-bridge-2.0.pc
/usr/lib32/pkgconfig/atk-bridge-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/modules/libatk-bridge.so
/usr/lib64/libatk-bridge-2.0.so.0
/usr/lib64/libatk-bridge-2.0.so.0.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/gtk-2.0/modules/libatk-bridge.so
/usr/lib32/libatk-bridge-2.0.so.0
/usr/lib32/libatk-bridge-2.0.so.0.0.0
