#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : at-spi2-atk
Version  : 2.38.0
Release  : 28
URL      : https://download.gnome.org/sources/at-spi2-atk/2.38/at-spi2-atk-2.38.0.tar.xz
Source0  : https://download.gnome.org/sources/at-spi2-atk/2.38/at-spi2-atk-2.38.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: at-spi2-atk-lib = %{version}-%{release}
Requires: at-spi2-atk-license = %{version}-%{release}
BuildRequires : at-spi2-core-dev
BuildRequires : atk-dev
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : glib-dev
BuildRequires : libxml2-dev

%description
D-Bus AT-SPI
------------
This version of at-spi is a major break from version 1.x.
It has been completely rewritten to use D-Bus rather than
ORBIT / CORBA for its transport protocol.

%package dev
Summary: dev components for the at-spi2-atk package.
Group: Development
Requires: at-spi2-atk-lib = %{version}-%{release}
Provides: at-spi2-atk-devel = %{version}-%{release}
Requires: at-spi2-atk = %{version}-%{release}

%description dev
dev components for the at-spi2-atk package.


%package lib
Summary: lib components for the at-spi2-atk package.
Group: Libraries
Requires: at-spi2-atk-license = %{version}-%{release}

%description lib
lib components for the at-spi2-atk package.


%package license
Summary: license components for the at-spi2-atk package.
Group: Default

%description license
license components for the at-spi2-atk package.


%prep
%setup -q -n at-spi2-atk-2.38.0
cd %{_builddir}/at-spi2-atk-2.38.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600302641
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/at-spi2-atk
cp %{_builddir}/at-spi2-atk-2.38.0/COPYING %{buildroot}/usr/share/package-licenses/at-spi2-atk/01a6b4bf79aca9b556822601186afab86e8c4fbf
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-settings-daemon-3.0/gtk-modules/at-spi2-atk.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/at-spi2-atk/2.0/atk-bridge.h
/usr/lib64/libatk-bridge-2.0.so
/usr/lib64/pkgconfig/atk-bridge-2.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/modules/libatk-bridge.so
/usr/lib64/libatk-bridge-2.0.so.0
/usr/lib64/libatk-bridge-2.0.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/at-spi2-atk/01a6b4bf79aca9b556822601186afab86e8c4fbf
